// Generated by rstantools.  Do not edit by hand.

/*
    test is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    test is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with test.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.26.1-4-gd72b68b7-dirty
#include <stan/model/model_header.hpp>
namespace model_fix_ind_namespace {
inline void validate_positive_index(const char* var_name, const char* expr,
                                    int val) {
  if (val < 1) {
    std::stringstream msg;
    msg << "Found dimension size less than one in simplex declaration"
        << "; variable=" << var_name << "; dimension size expression=" << expr
        << "; expression value=" << val;
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
inline void validate_unit_vector_index(const char* var_name, const char* expr,
                                       int val) {
  if (val <= 1) {
    std::stringstream msg;
    if (val == 1) {
      msg << "Found dimension size one in unit vector declaration."
          << " One-dimensional unit vector is discrete"
          << " but the target distribution must be continuous."
          << " variable=" << var_name << "; dimension size expression=" << expr;
    } else {
      msg << "Found dimension size less than one in unit vector declaration"
          << "; variable=" << var_name << "; dimension size expression=" << expr
          << "; expression value=" << val;
    }
    std::string msg_str(msg.str());
    throw std::invalid_argument(msg_str.c_str());
  }
}
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using std::pow;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::model_base_crtp;
using stan::model::rvalue;
using stan::model::cons_list;
using stan::model::index_uni;
using stan::model::index_max;
using stan::model::index_min;
using stan::model::index_min_max;
using stan::model::index_multi;
using stan::model::index_omni;
using stan::model::nil_index_list;
using namespace stan::math;
using stan::math::pow; 
stan::math::profile_map profiles__;
static int current_statement__= 0;
static const std::vector<string> locations_array__ = {" (found before start of program)",
                                                      " (in 'fix_ind', line 10, column 2 to column 35)",
                                                      " (in 'fix_ind', line 11, column 2 to column 36)",
                                                      " (in 'fix_ind', line 14, column 2 to column 19)",
                                                      " (in 'fix_ind', line 15, column 2 to column 22)",
                                                      " (in 'fix_ind', line 16, column 2 to column 34)",
                                                      " (in 'fix_ind', line 17, column 2 to column 30)",
                                                      " (in 'fix_ind', line 25, column 2 to column 24)",
                                                      " (in 'fix_ind', line 26, column 2 to column 24)",
                                                      " (in 'fix_ind', line 27, column 2 to column 34)",
                                                      " (in 'fix_ind', line 28, column 2 to column 25)",
                                                      " (in 'fix_ind', line 20, column 2 to column 30)",
                                                      " (in 'fix_ind', line 21, column 2 to column 31)",
                                                      " (in 'fix_ind', line 22, column 2 to column 32)",
                                                      " (in 'fix_ind', line 2, column 2 to column 18)",
                                                      " (in 'fix_ind', line 3, column 9 to column 10)",
                                                      " (in 'fix_ind', line 3, column 2 to column 18)",
                                                      " (in 'fix_ind', line 4, column 2 to column 20)",
                                                      " (in 'fix_ind', line 5, column 2 to column 20)",
                                                      " (in 'fix_ind', line 6, column 2 to column 21)",
                                                      " (in 'fix_ind', line 7, column 2 to column 21)"};
#include <stan_meta_header.hpp>
class model_fix_ind final : public model_base_crtp<model_fix_ind> {
private:
  int N;
  Eigen::Matrix<double, -1, 1> y;
  double L_m;
  double U_m;
  double L_cv;
  double U_cv;
 
public:
  ~model_fix_ind() { }
  
  inline std::string model_name() const final { return "model_fix_ind"; }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.26.1-4-gd72b68b7-dirty", "stancflags = "};
  }
  
  
  model_fix_ind(stan::io::var_context& context__,
                unsigned int random_seed__ = 0,
                std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static const char* function__ = "model_fix_ind_namespace::model_fix_ind";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      current_statement__ = 14;
      context__.validate_dims("data initialization","N","int",
          context__.to_vec());
      N = std::numeric_limits<int>::min();
      
      current_statement__ = 14;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 14;
      current_statement__ = 14;
      check_greater_or_equal(function__, "N", N, 0);
      current_statement__ = 15;
      validate_non_negative_index("y", "N", N);
      current_statement__ = 16;
      context__.validate_dims("data initialization","y","double",
          context__.to_vec(N));
      y = Eigen::Matrix<double, -1, 1>(N);
      stan::math::fill(y, std::numeric_limits<double>::quiet_NaN());
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 16;
        assign(y_flat__, nil_index_list(), context__.vals_r("y"),
          "assigning variable y_flat__");
        current_statement__ = 16;
        pos__ = 1;
        current_statement__ = 16;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          current_statement__ = 16;
          assign(y, cons_list(index_uni(sym1__), nil_index_list()),
            y_flat__[(pos__ - 1)], "assigning variable y");
          current_statement__ = 16;
          pos__ = (pos__ + 1);}
      }
      current_statement__ = 17;
      context__.validate_dims("data initialization","L_m","double",
          context__.to_vec());
      L_m = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 17;
      L_m = context__.vals_r("L_m")[(1 - 1)];
      current_statement__ = 17;
      current_statement__ = 17;
      check_greater_or_equal(function__, "L_m", L_m, 0);
      current_statement__ = 18;
      context__.validate_dims("data initialization","U_m","double",
          context__.to_vec());
      U_m = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 18;
      U_m = context__.vals_r("U_m")[(1 - 1)];
      current_statement__ = 18;
      current_statement__ = 18;
      check_greater_or_equal(function__, "U_m", U_m, 0);
      current_statement__ = 19;
      context__.validate_dims("data initialization","L_cv","double",
          context__.to_vec());
      L_cv = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 19;
      L_cv = context__.vals_r("L_cv")[(1 - 1)];
      current_statement__ = 19;
      current_statement__ = 19;
      check_greater_or_equal(function__, "L_cv", L_cv, 0);
      current_statement__ = 20;
      context__.validate_dims("data initialization","U_cv","double",
          context__.to_vec());
      U_cv = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 20;
      U_cv = context__.vals_r("U_cv")[(1 - 1)];
      current_statement__ = 20;
      current_statement__ = 20;
      check_greater_or_equal(function__, "U_cv", U_cv, 0);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    num_params_r__ = 0U;
    
    try {
      num_params_r__ += 1;
      num_params_r__ += 1;
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI, stan::require_vector_like_t<VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    static const char* function__ = "model_fix_ind_namespace::log_prob";
(void) function__;  // suppress unused var warning
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      local_scalar_t__ m;
      m = DUMMY_VAR__;
      
      current_statement__ = 1;
      m = in__.scalar();
      current_statement__ = 1;
      if (jacobian__) {
        current_statement__ = 1;
        m = stan::math::lub_constrain(m, L_m, U_m, lp__);
      } else {
        current_statement__ = 1;
        m = stan::math::lub_constrain(m, L_m, U_m);
      }
      local_scalar_t__ cv;
      cv = DUMMY_VAR__;
      
      current_statement__ = 2;
      cv = in__.scalar();
      current_statement__ = 2;
      if (jacobian__) {
        current_statement__ = 2;
        cv = stan::math::lub_constrain(cv, L_cv, U_cv, lp__);
      } else {
        current_statement__ = 2;
        cv = stan::math::lub_constrain(cv, L_cv, U_cv);
      }
      local_scalar_t__ mu;
      mu = DUMMY_VAR__;
      
      local_scalar_t__ sigma;
      sigma = DUMMY_VAR__;
      
      current_statement__ = 5;
      mu = stan::math::log((m / stan::math::sqrt((1 + pow(cv, 2)))));
      current_statement__ = 6;
      sigma = stan::math::sqrt(stan::math::log((1 + pow(cv, 2))));
      current_statement__ = 4;
      current_statement__ = 4;
      check_greater_or_equal(function__, "sigma", sigma, 0);
      {
        current_statement__ = 11;
        lp_accum__.add(uniform_lpdf<propto__>(m, L_m, U_m));
        current_statement__ = 12;
        lp_accum__.add(uniform_lpdf<propto__>(cv, L_cv, U_cv));
        current_statement__ = 13;
        lp_accum__.add(normal_lpdf<propto__>(stan::math::log(y), mu, sigma));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, stan::require_std_vector_vt<std::is_floating_point, VecVar>* = nullptr>
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.resize(0);
    stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
    static const char* function__ = "model_fix_ind_namespace::write_array";
(void) function__;  // suppress unused var warning
    (void) function__;  // suppress unused var warning
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    
    try {
      double m;
      m = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      m = in__.scalar();
      current_statement__ = 1;
      m = stan::math::lub_constrain(m, L_m, U_m);
      double cv;
      cv = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      cv = in__.scalar();
      current_statement__ = 2;
      cv = stan::math::lub_constrain(cv, L_cv, U_cv);
      double mu;
      mu = std::numeric_limits<double>::quiet_NaN();
      
      double sigma;
      sigma = std::numeric_limits<double>::quiet_NaN();
      
      vars__.emplace_back(m);
      vars__.emplace_back(cv);
      if (logical_negation((primitive_value(emit_transformed_parameters__) ||
            primitive_value(emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 5;
      mu = stan::math::log((m / stan::math::sqrt((1 + pow(cv, 2)))));
      current_statement__ = 6;
      sigma = stan::math::sqrt(stan::math::log((1 + pow(cv, 2))));
      current_statement__ = 4;
      current_statement__ = 4;
      check_greater_or_equal(function__, "sigma", sigma, 0);
      if (emit_transformed_parameters__) {
        vars__.emplace_back(mu);
        vars__.emplace_back(sigma);
      } 
      if (logical_negation(emit_generated_quantities__)) {
        return ;
      } 
      double x_tilde;
      x_tilde = std::numeric_limits<double>::quiet_NaN();
      
      double y_tilde;
      y_tilde = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 9;
      x_tilde = normal_rng(mu, sigma, base_rng__);
      current_statement__ = 10;
      y_tilde = stan::math::exp(x_tilde);
      current_statement__ = 8;
      current_statement__ = 8;
      check_greater_or_equal(function__, "y_tilde", y_tilde, 0);
      vars__.emplace_back(x_tilde);
      vars__.emplace_back(y_tilde);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, stan::require_std_vector_t<VecVar>* = nullptr, stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void transform_inits_impl(const stan::io::var_context& context__,
                                   VecI& params_i__, VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    vars__.clear();
    vars__.reserve(num_params_r__);
    
    try {
      int pos__;
      pos__ = std::numeric_limits<int>::min();
      
      pos__ = 1;
      double m;
      m = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      m = context__.vals_r("m")[(1 - 1)];
      double m_free__;
      m_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 1;
      m_free__ = stan::math::lub_free(m, L_m, U_m);
      double cv;
      cv = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      cv = context__.vals_r("cv")[(1 - 1)];
      double cv_free__;
      cv_free__ = std::numeric_limits<double>::quiet_NaN();
      
      current_statement__ = 2;
      cv_free__ = stan::math::lub_free(cv, L_cv, U_cv);
      vars__.emplace_back(m_free__);
      vars__.emplace_back(cv_free__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
      // Next line prevents compiler griping about no return
      throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***"); 
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__.clear();
    names__.emplace_back("m");
    names__.emplace_back("cv");
    names__.emplace_back("mu");
    names__.emplace_back("sigma");
    names__.emplace_back("x_tilde");
    names__.emplace_back("y_tilde");
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    dimss__.clear();
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    dimss__.emplace_back(std::vector<size_t>{});
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "m");
    param_names__.emplace_back(std::string() + "cv");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "mu");
      param_names__.emplace_back(std::string() + "sigma");
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "x_tilde");
      param_names__.emplace_back(std::string() + "y_tilde");
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "m");
    param_names__.emplace_back(std::string() + "cv");
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "mu");
      param_names__.emplace_back(std::string() + "sigma");
    }
    
    if (emit_generated_quantities__) {
      param_names__.emplace_back(std::string() + "x_tilde");
      param_names__.emplace_back(std::string() + "y_tilde");
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"m\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"cv\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"x_tilde\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"y_tilde\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    stringstream s__;
    s__ << "[{\"name\":\"m\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"cv\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"mu\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"x_tilde\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"},{\"name\":\"y_tilde\",\"type\":{\"name\":\"real\"},\"block\":\"generated_quantities\"}]";
    return s__.str();
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      std::vector<double> vars_vec(vars.size());
      std::vector<int> params_i;
      write_array_impl(base_rng, params_r, params_i, vars_vec,
          emit_transformed_parameters, emit_generated_quantities, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i) {
        vars.coeffRef(i) = vars_vec[i];
      }
    }
    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      write_array_impl(base_rng, params_r, params_i, vars, emit_transformed_parameters, emit_generated_quantities, pstream);
    }
    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }
  
    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits_impl(context, params_i, params_r_vec, pstream);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i) {
        params_r.coeffRef(i) = params_r_vec[i];
      }
    }
    inline void transform_inits(const stan::io::var_context& context,
                                std::vector<int>& params_i,
                                std::vector<double>& vars,
                                std::ostream* pstream = nullptr) const final {
      transform_inits_impl(context, params_i, vars, pstream);
    }        
};
}
using stan_model = model_fix_ind_namespace::model_fix_ind;
#ifndef USING_R
// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_fix_ind_namespace::profiles__;
}
#endif
#endif
